### PR TITLE
fix(api): use `Array.find` to compare answers 💪

### LINKED ISSUE #69: Every student is having high similar scores

### PR DESCRIPTION
**Pull request by iammola**
Closes #69.

### CODE REVIEW

File: pages/api/students/[id]/cbt_results.ts [hunk 1]
```diff
@@ -30,37 +30,35 @@ async function createResult(_id: any, result: RequestBody): Promise<ServerRespon
...
-            },
-          },
-        },
-      },
+      ]),
     ]);
 
+    if (alreadyAnswered) throw new Error("Exam already answered");
     const answers = Object.entries(result.answers).reduce((acc, [question, answer]) => {
-      score += +!!exam.answers.findIndex((a) => a._id.equals(answer));
```
Comment (iammola) [inline pages/api/students/[id]/cbt_results.ts:63]: I remember I had just finished typing out the code. I wanted a short one-liner that'll be nice to look at. Then I considered using `Array.findIndex` since it returns a number, but it was too long and I removed the `> -1` part I had added but forgot to change the `findIndex`, back to `find`.

This job's too delicate LMAO
